; PlatformIO Project Configuration File
; 
;   default_envs: environment/device that will be compiled to

[platformio]
default_envs = esp32-dev
description = ARCOS

[env:arduino-uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_flags = 
  -DTARGET_AVR_Atmega328p_Uno
  -std=c++17

[env:esp32-dev]
platform = espressif32
board = esp32dev
board_build.mcu = esp32
framework = espidf
board_build.f_cpu = 240000000L
board_build.flash_size = 2MB
monitor_speed = 115200
build_flags = 
  -DTARGET_ESP32_Wroom32S2_Esp32Dev
  -std=c++17
