; PlatformIO Project Configuration File
; 
;   default_envs: environment/device that will be compiled to

[platformio]
default_envs = arduino-uno

[env:arduino-uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_flags = -DTARGET_AVR_Atmega328p_Uno
