;*****************************************************************
;   File:      platformio.ini
;   Category:  mcu configuration
;   Author:    XCR1793 (Feather Forge)
;  
;   Purpose:
;       Configures the environment in which the mcu is compiled and
;       manages other build variables.
;
;   Note:
;       default_envs: Environment/device that will be compiled to.
;*****************************************************************

[platformio]
default_envs = esp32s3-module
description = ARCOS

[env:arduino-uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_flags = 
  -DTARGET_AVR_Atmega328p_Uno
  -std=c++17

[env:esp32s2-dev]
platform = espressif32
board = esp32dev
board_build.mcu = esp32
framework = espidf
board_build.f_cpu = 240000000L
board_build.flash_size = 2MB
monitor_speed = 115200
build_flags = 
  -DTARGET_ESP32_Wroom32S2_Esp32Dev
  -std=c++17

[env:esp32s3-module]
platform = espressif32
board = esp32s3usbotg
framework = espidf
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT
  -DTARGET_ESP32_Wroom32S3_Module
  -std=c++17