; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32s3-module
description = ARCOS

[env:arduino-uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_flags = 
	-DTARGET_AVR_Atmega328p_Uno
	-std=c++17
lib_deps = adafruit/Adafruit GFX Library@^1.12.1

[env:esp32s2-dev]
platform = espressif32
board = esp32dev
board_build.mcu = esp32
framework = espidf
board_build.f_cpu = 240000000L
board_build.flash_size = 2MB
monitor_speed = 115200
build_flags = 
	-DTARGET_ESP32_Wroom32S2_Esp32Dev
	-std=c++17
lib_deps = adafruit/Adafruit GFX Library@^1.12.1

[env:esp32s3-module]
platform = espressif32 @ 6.12.0
board = esp32s3usbotg
framework = espidf
monitor_speed = 115200
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT
	-DTARGET_ESP32_Wroom32S3_Module
	-std=c++17
lib_deps =
  ; adafruit/Adafruit GFX Library@^1.12.1
  ; https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA.git
	https://github.com/TobleMiner/esp_i2s_parallel.git